version: "3.9"
services: 
  ascii:
    image: asciidoctor/docker-asciidoctor
    command: "asciidoctor-pdf -r asciidoctor-bibtex inno.adoc asd.adoc bep3.adoc"
    volumes:
      - "./src/docs/asciidoc:/documents"