version: "3.9"
services: 
  ascii:
    image: asciidoctor/docker-asciidoctor
    command: "asciidoctor-pdf -o ./target/inno.pdf -v -r asciidoctor-bibtex -r asciidoctor-diagram ./src/docs/asciidoc/inno.adoc"
    volumes:
      - ".:/documents"
  ascii-html:
    image: asciidoctor/docker-asciidoctor
    command: "asciidoctor -o ./target/index.html -v -r asciidoctor-bibtex -r asciidoctor-diagram ./src/docs/asciidoc/inno.adoc"
    volumes:
      - ".:/documents"
  