== Gedistribueerde Systemen

=== Leerdoel

[quote]
“De student kan systemen, en niet slechts applicaties ontwikkelen, die in z'n geheel een echt probleem oplossen.” 


=== Inleiding

[quote, Leslie Lamport]
“A distributed system is one in which the failure of a computer you didn't even know existed can render your own computer unusable.” 

Tot nu toe heb je in je opleiding applicaties gemaakt die bepaalde problemen voor je stakeholders oplossen.
Dat is een nobel begin, maar vaak staan deze applicaties niet op zichzelf en wordt het tijd om na te denken over 
groepen applicaties die samen nog steeds de problemen van je stakeholders oplossen.

Zo'n groep applicaties die samen een doel dienen noemen we een gedistribueerd systeem. En die dingen hebben
de verdiende reputatie om erg ingewikkeld te worden.

=== Voorbeelden


[quote, Tanenbaum & Van Steen (2017)]
"A distributed system is a collection of independent computers that appears to its users as a single coherent system."


==== Satelieten

==== Whatsapp

==== Bitcoin

=== Waarom?

Redenen tot distributie:

* Fysieke redenen
* Performance / schaalbaarheid
* Reliability / fault-tolerance
* Integratie bestaande systemen

Distribution Transparancy

* Access
* Location
* Replication
* Concurrency
* Failure

=== Waarom niet?

Fallacies:

* The network is reliable
* Latency is zero
* Bandwidth is infinite
* The network is secure
* The topology does not change
* There is one administrator
* Transport cost is zero
* The network is homogenous

=== Voorbeelden

==== Databases

==== Microservices

==== Doodnornale webapp

=== Integratiestijlen

* File Transfer
* Shared Database
* RPC
* Messaging

eeeh, wat is hier aan de hand?

