== Remote Procedure Calls

Remote Procedure Calls zijn de meest klassieke vorm van communicatie tussen systemen. Zeker in object-georiënteerde talen is het al sinds de jaren 90 (CORBA, later SOAP etc. [TODO:2 ref]) een wijd-verspreide stijl van communicatie.

[source, java]
----
//PaymentService is in dit geval een Interface
private PaymentService paymentService;

public void generatePayment(Order o){
    //allerhande code om van Order naar betaling te komen...
    PaymentLink link = paymentService.createPaymentLink(o.getPaymentDetails());
    //en de rest van je applicatielogica
}

----

Van OOP hebben we geleerd dat we hele verschillende implementaties kunnen schrijven voor die payment-service. Wie weet is die payment-link zo simpel dat we 'm kunnen genereren door puur een String op een bepaalde manier te formatten? Dan kunnen we de hele operatie binnen ons proces uitvoeren. Dit noemen we dan een _lokale_ service aanroep.
Bij veel betalings-services moet je zo'n betaling echter eerst expliciet aanmelden, dus dan stuur je een Request naar hun service, en met de benodigde informatie in de Response om de link te genereren: Het mooie van deze interface is dat we dat verschil nu niet zien! Dit noemen we dan een _remote_ service aanroep.

Dit is de kerngedachte van een Remote-Procedure integratiestijl. We kunnen procedures (of methods, of functies, we gebruiken de term niet heel precies) aanroepen in andere services, _net zoals_ we dat voor lokale services doen.

=== Nadelen RPC

Zoals opgemerkt is het grote voordeel van een RPC interface dat je het verschil tussen een lokale en een remote aanroep niet kan zien. Het grootste nadeel van een RPC interface is echter dat we dat verschil nu niet kunnen zien!

[quote, Fowler (2003)]
"First Law of Distributed Object Design: Don't distribute your objects!"

Als we terugdenken aan de Fallacies of Distributed Systems (<<fallacies>>) willen we misschien juist weten of er hier een remote-procedure call achter schuil gaat!

[source, java]
----
//Dit is waarschijnlijk wel redelijk:
Order order = //... ergens komt een order vandaan.
PaymentLink link = paymentService.createPaymentLink(order.getPaymentDetails());

//Dit is echter vragen om problemen!:
List<Order> orders = //... ergens komt een lijst van 100+ orders vandaan.
List<PaymentLink> links = new ArrayList<>();
for(Order o: orders){
    PaymentLink link = paymentService.createPaymentLink(o.getPaymentDetails());
    links.add(link);
}

----

Het probleem hier is dat in de for-loop er 100+ keer een los netwerkbericht naar een externe service wordt gestuurd. Dit is heel traag en foutgevoelig. En het vervelende is, je _ziet_ het niet als programmeur. We hebben een te sterke abstractie gemaakt, het verbergt teveel!

In recente jaren is het steeds gebruikelijker aan het worden om dit soort interfaces te wrappen in een extra laagje dat aangeeft dat het mogelijk lang duurt om een reactie te krijgen. Zo'n extra laagje noemen we in Javascript een Promise, in C# een Task, in Python een Future, en in Java een Monofootnote:[Java heeft meerdere populaire libraries, zoals Project Reactor, of RXJava. Het heet overal net iets anders. Spring gebruikt Reactor, en die noemt het een Mono.]. Er zijn kleine verschillen tussen de talen en libraries, maar in de basis is het idee hetzelfde.

Een ander nadeel is dat RPC bijna altijd gekoppeld is aan de communicatiewijze (Zie <<Communicatiewijzes>>) Request-Reply. Dit betekent dat het alle fragiliteit van die communicatiewijze heeft. Ook bij methodes die niets returnen (_void_) die technisch gezien via een Fire & Forget wijze gecommuniceerd zouden kunnen worden heeft het onderliggende protocol vaak nog een lege success-Response. Zodoende is het belangrijk om voor kritieke RPC-paden in je applicatie een goede High-Availibility oplossing te overwegen (<<availability>> zullen we later behandelen), of anderzijds een tijdelijke onderbreking te kunnen accepteren.

Al met al is RPC een veelvoorkomende integratiestijl en van de methoden die we in deze cursus behandelen de meest intuïtieve. Er zijn nadelen, zowel qua API als qua implementatie, maar die kunnen enigszins gemitigeerd worden.

=== Stijlen RPC

==== REST

Tot nog toe hebben we vooral webservices gemaakt die door een client-side stuk javascript, vaak door middel van _fetches_ aangeroepen wordt. Zodoende hebben we vooral REST-APIs voor Postman en onze eigen frontends gemaakt.

Er is natuurlijk geen enkele reden waarom we niet vanuit andere talen en contexten (zoals onze eigen backends) ook calls naar andere REST-services zouden kunnen maken. In jaar 1 moest je bijv. in Python een weer-API uitvragenfootnote:[Of zoiets, de opdracht wil nog wel eens veranderen].

REST als een vorm van RPC zien is helaas een beetje verwarrend. Bij REST willen we een Resource-Oriented API ontwikkelen, dat betekent dat we de Resources (de "dingen") leidend willen laten zijn. Dit zorgt voor die standaard URL verdelingen die we eerder hebben gezien:

[cols="1,1"]
|===
|_GET_ /persons
|vraagt een lijst van alle personen

|_GET_ /persons/{id}
|vraagt een enkel persoon op, namelijk die met een bepaald {id}

|_POST_ /persons
|voeg een persoon toe aan de lijst, met de details in de request body

|_DELETE_ /persons/{id}
|verwijdert een enkel persoon

|_PUT_ /persons/{id}
|vervangt de gegevens van een persoon (strict genomen in z'n geheel)

|_PATCH_ /persons/{id}
|doet een partiële update van een bepaald persoon

|===

Deze stijl van ontwikkelen, waarbij de 'dingen' (resources) centraal staan, en de HTTP-verbs (GET,PUT, POST, etc.) de mogelijke handelingen voorstellen is relatief flexibel en eenvoudig te doorgronden.

Dit kun je contrasteren met een RPC-API, waarbij je bijv. een _POST_ doet naar _/persons/maaknieuw_, of _/updateperson_, of desnoods zoiets als _/api_, waarbij dan de requestbody zoiets bevat als _{"method": "updateperson"}_. Deze stijl van API noemt men een RPC-API, omdat je feitelijk ook qua contractstijl expliciet een bepaalde method (als synoniem van procedure) in de andere service aanroept. 

Het is onfortuinlijk dat we dus twee verschillende betekenissen van het woord RPC door elkaar gebruiken. In het oude geval was RPC het tegenovergestelde van de Resource-Oriented-stijl van REST (misschien was Procedure-Oriented een mooier woord geweest). In dit vak is RPC als communicatiewijze een alternatief van Messaging, we doelen daarmee dus op een process waarbij een call naar een externe  service wordt ge-encapsuleerd als (bijna?) een lokale call.


===== Task-based REST

Het is relatief eenvoudig om CRUD services (services die create, read, update & delete functionaliteit aanbieden) op entities via REST aan te bieden. Je koppelt een controller aan een Repository. Met een POST save je dan een nieuwe entity, met een GET kun je een find method aanroepen, met een PUT wederom een (updatende) save, en je zult nooit raden wat we met DELETE doen...

Maar wat doe je als de applicatie ingewikkelder wordt?

Stel we hebben groothandel, die containerladingen vol electronica over de Atlantische Oceaan verscheept en een winkelketen als klant die zaken inkoopt. Zo'n bedrijf heeft vaak enorm veel contacten over de hele wereld, en zou het best fijn vinden om als service aan te kunnen bieden dat bedrijven hun bestelling nog een klein beetje kunnen aanpassen (voor een extra bedrag natuurlijk).

Dus stel winkelketen MM merkt dat het net teveel TV's heeft besteld, maar ja, die zijn al onderweg met de container. Er is een best goede kans dat de groothandel die Tvs binnen afzienbare tijd bij één van diens andere klanten kwijt zou kunnen (misschien voor een kleine korting, maar kleiner dan het bedrag dat MM extra betaald). En als het allemaal niet lukt voordat de schepen uitgeladen moeten worden, tja, dan heeft winkelketen MM pech en moet alsnog de originele factuur voldaan worden.

In dit soort gevallen ga je er waarschijnlijk niet komen met een standaard entity-based REST-ful model. Dan heb je waarschijnlijk een resource _/orders_, en als je dan dus iets minder TVs wil bestellen, wat doe je dan?

Je zou kunnen proberen te gaan PUTten of PATCHen op bijv. _/orders/764_, maar de verwachting is dan dat je die resource aanpast, en dat je dan vervolgens een GET naar diezelfde URL kan doen, om direct het resultaat te zien.

Een veel gebruikte oplossing in de praktijk is dat je de neiging om alles als resources te modelleren even loslaat. En dan heb je toch een paar 'Remote Procedure'-oriented urls, zoals bijv. _/orders/764/requestOrderChange_. Daar kun je dan naartoe POSTen (want POST heeft de minste regels), en dan krijg je een result terug (de REST regels hebben we toch al opgegeven, dus je kunt doen wat je wil). Aangezien het overduidelijk geen RESTful url is, is er ook geen verwachting dat een GET naar _/orders/764/requestOrderChange_ iets nuttigs gaat opleveren.

Maar kan het niet netter? Een relatief simpele manier is om er 'even anders tegenaan te kijken'. Nu maken we van onze entities de resources, maar wat als we juist van onze usecases de resources maken? We zouden 'de verzochte wijzigingen aan een order' als resource kunnen bestempelen: _/orders/764/orderChanges_. Als dit de resource is, dan kunnen wijzigingsverzoeken gePOST worden, vervolgens krijgen we volgens RESTful standaarden een Location-header terug, en kunnen we op zeg _/orders/764/changes/1_ kijken wat de status is van die wijziging. We zouden 'm zelfs kunnen proberen te PUTen (nog meer TVs!) of DELETEn (toch maar geen extra TVs). Kortom, niet alleen de originele usecase heeft een plekje gekregen, maar ons ontwerp bedelt ons om nog meer handige functionaliteit te implementeren!

Uiteraard zullen er altijd een paar vreemde eenden overblijven. Het meest bekende voorbeeld zien we op urls als _/login_ en _/logout_. Dit heeft z'n grondvesten in het feit dat naast de REST-structuur, we ook nog de klassieke HTML-paginas hebben. Daar kan men een formulier (<form>) definiëren, en dat vervolgens opsturen naar een url middels een POST. De login use-case past prima in zo'n 'formulier-verwerkings'-stroom, maar niet in een standaard Resource-oriented setup. We POSTen er welliswaar iets naartoe, maar het voelt niet logisch om vervolgens een lijst van logins te krijgen als je een GET doet naar _/login_. 

Het organiseren van je applicatie in resources (zowel entities, als usecases, of acties) is dus een goede richtlijn, en er zullen altijd een paar uitzonderingen blijven. Soms heb je ook gewoon meer tijd nodig om de juiste resources te ontdekken, dus blijf vooral niet geforceerd proberen overal resources van te maken. Gebruik het als het past. 

===== Richardson Maturity Model

In Restful Web Services cite:[richardson_webservices] geeft Richardson een mooi overzicht van de filosofie achter REST. De meest beroemde toevoeging is echter het Richardson maturity model cite:[richardson_maturity]. Flauw gezegd heeft elke API een bepaald level:

[cols="1,2"]
|===
| Level 0
| Urls betekenen niets. HTTP verbs ook niet. Maar hey, het werkt. Denk aan een enkel _/api_ endpoint, waar je alles naartoe _POST_

| Level 1
| Urls betekenen iets, maar qua HTTP verbs doen we maar wat. (vaak de klassieke 'alles is een POST'-services)

| Level 2
| Urls betekenen iets, en HTTP verbs betekenen iets. Dit is onze standaard tot nu toe.

| Level 3
| Level 2 + Hypermedia: HatEoAS
|===

De gedachte achter HatEoAS, een verschrikkelijke afkorting die staat voor Hypermedia as the Engine of Application State, is precies dezelfde stap als van Text naar Hypertext (de HT van HTTP): Text, of Media (zoals JSON, XML, etc.) is tof, maar het wordt pas echt tof (hypertof, zeg maar) als de stukken tekst en data naar elkaar gaan verwijzen. Dit is de basis van het toch best wel succesvolle 'World Wide Web'.

****
Persoonlijk heb ik soms enigszins moeite met REST level 3. Er is absoluut niets tegen een collectietje links in je response-documenten. En als je moet kiezen voor een (publiek!) id voor je entity is vaak "customerid: 3785" een stuk minder informatief dan customerid: https://myapi.example.org/customers/3785. Die tweede optie kost een stuk meer bytes, maar elke client weet dan ook precies waar verdere informatie gezocht kan worden.

Aan de andere kant heb je dan weer vrij pittige standaarden als https://jsonapi.org/[JSON:API]. Deze standaarden zorgen er voor dat je allerlei randgevallen netjes kan afhandelen, maar de prijs die je betaalt is wel dat je ... nouja... vrij lelijke JSON returnt. En het is me niet altijd direct duidelijk waarom dat steekt? Waarom zou ons serializatie-format mooi moeten zijn? Maar steken doet het.

Een andere interessante stelling vind je bij één van mijn favoriete auteurs: https://blog.ploeh.dk/2013/05/01/rest-lesson-learned-avoid-hackable-urls/[Mark Seemann over Hackable URLs]. In die post lezen we dat als we HatEoAS hanteren, dat we dan eigenlijk ook al onze voorheen-leesbare REST-2 urls compleet onleesbaar moeten maken, zodat we clients _dwingen_ ook daadwerkelijk alleen de links te gebruiken. 

De combinatie van deze twee adviezen lijkt me helemaal interessant: dan zou je om een REST-3-API te worden zowel je URLs moeten slopen, als de leesbaarheid van je responses omlaag moeten halen. Ik snap de redenaties, en ik zie er geen gaten in, maar toch kan ik moeilijk uit de voeten met de conclusie. 

Maar misschien jij wel? Laat 't me vooral weten!

-Tom
****


==== SOAP & GRPC

SOAP is een oud RPC-protocol waarbij we lijvige XML-documenten sturen als Request en Response. Deze werden meestal over HTTP verstuurd, maar soms ook over andere communicatiemedia. Bij SOAP (en GRPC) is het basisidee dat er een programmeertaal-onafhankelijke service definition file is (een WSDL file voor SOAP, een Protobuf file voor GRPC), waaruit voor meerdere programmeertalen een skelet van code gegenereerd kan worden voor elke operatie die de service aanbiedt, of elke data-structuur die als parameter of return-waarde dient voor deze operaties.

Op zich is dit geen gek idee. Het is dus jammer dat dit bij SOAP een beetje stuk liep op het feit dat elke programmeertaal dit skelet -net- even anders genereerde, waardoor het in de praktijk toch een hele hoop gedoe was om verschillende talen met elkaar te laten praten.

GRPC gebruikt geen XML, maar Protobuf over (de lower-level delen van ) het HTTP/2 protocol. In de basis heeft het veel overeenkomsten met SOAP, maar het is een heel stuk efficienter (en ook efficienter dan bijv. REST). Tot nu toe lijkt het drama qua implementaties van SOAP achterwege te blijven, maar dat komt waarschijnlijk voornamelijk omdat de organisatie achter GRPC (Google RPC) bijna alle clients zelf gebouwd en ge-opensourced heeft.

Een nadeel is dat er geen goede (browser-)javascript SOAP of GRPC clients zijn, dus deze protocollen zijn voor server-server communicatie.

[TODO:2 voorbeelden!]


==== GraphQL

GraphQL is een project van Facebook waarin je een bepaald datamodel direct kan exposen als API. Dus je maakt een datamodel, en je hebt maar één endpoint nodig om vervolgens je clients zelf hun eigen queries en operaties te laten schrijven.

Dit is tegelijkertijd de grootste kracht, en de grootste zwakte. Het is superflexibel, maar het is ook verdraaid lastig om alle mogelijke queries performant te houden.

[TODO:2 voorbeelden!]

[#multipom]
=== Multi-project-POMs (Java-specifiek)

==== Maven refresher

==== Gespleten POMs, BOMs, en meer


