name: Build

on:
  push:
    branches: [ "main", "cicd" ]
  pull_request:
    branches: [ "main", "cicd" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site
      run: |
        docker compose run ascii